name: Update Dashboard Image

on:
  schedule:
    - cron: "0 * * * *"  # Cada hora
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Descargar dashboard
        run: wget -O dashboard.png "https://morada-uno.metabaseapp.com/public/question/6ffd5471-a42f-43cd-9eef-52e2e0476c45"

      - name: Subir cambios a GitHub
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add dashboard.png
          git commit -m "Actualización automática del dashboard"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/gabrielatMoradaUno/DashLive.git
